Vagrant.configure("2") do |config|
  config.vm.define "client" do |client|
    client.vm.box = "debian/bullseye64"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.1.11"
    client.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 1
    end
    client.vm.disk :disk, size: "10GB"

    # Installation des paquets
    client.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y curl
    SHELL

  end
end

