Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.box = "debian/bullseye64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.50.10"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--name", "server"]
    end
    server.vm.disk :disk, size: "10GB"

    # Installation des paquets
    server.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo apt install -y nginx nginx-extras ufw
    SHELL

  end
end

